version: '3.1'
services:
  postgresql:
    image: postgres:latest
    container_name: postgresql-sampledb1
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: sampledb1
      POSTGRES_USER: jed
      POSTGRES_PASSWORD: 12345678
    volumes:
      - ./data:/var/lib/postgresql/data
